version: '3'
services:

  postgres:
    image: docker.arvancloud.ir/postgres
    container_name: database
    environment:
      POSTGRES_USER: ehsan
      POSTGRES_PASSWORD: ehsan
      POSTGRES_DB: task_db
    ports:
      - "5432:5432"

  adminer:
    image: docker.arvancloud.ir/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres



